config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'destinations#index'
  # get 'search'
  resources :destinations, only: [:new, :create, :show, :edit, :update, :destroy] do



    resources :articles, only: [:create, :index, :show]
      collection do
        get 'search'
      end

 

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.search(search)
    if search != ""
      Article.where('detail LIKE(?)', "%#{search}%")
    else
      Destination.all
    end
  end


end

app/models/article.rb
class Article < ApplicationRecord

  belongs_to :destination
  belongs_to :user
  has_one_attached :image

  # validates :content, presence: true

  # def self.search(search)
  #   if search != ""
  #     Article.where('text LIKE(?)', "%#{search}%")
  #   else
  #     Article.all
  #   end
  # end

  # def save
    # article = Article.create(title: title, user_id: user_id, detail: detail, destination_id: destination_id)
  # end

end

app/models/bus_stop.rb
class BusStop < ActiveHash::Base
  self.data = [
    { id: 1, name: 'D1, D2' },
    { id: 2, name: 'B2, B3' },
    { id: 3, name: 'C4' },
    { id: 4, name: 'A1, A2, D1' },
    { id: 5, name: 'A3, B3' },
  ]

  include ActiveHash::Associations
  belongs_to :destination
  end

app/models/destination.rb
class Destination < ApplicationRecord
  has_many_attached :images
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :bus_stop
  belongs_to :line
  has_many :articles


  # def self.search(search)
  #   if search != ""
  #     Destination.joins(:articles).where('articles.detail LIKE(?)', "%#{search}%")
  #   else
  #     Destination.all
  #   end
  # end


  def self.search(search)
    if search != ""
      Article.where('detail LIKE(?)', "%#{search}%")
    else
      Destination.all
    end
  end

  # belongs_to :shipping_charger
  # belongs_to :shipping_from
  # belongs_to :days_to_shipping
  # belongs_to :user
  # has_one :order

  # with_options presence: true do
  #   validates :image
  #   validates :name
  #   validates :description
  #   validates :value,
  #             format: { with: /\A\d+\d\z/i, message: '半角数字で入力して下さい' },
  #             numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999, message: '300円以上9,999,999円以下で入力して下さい' }
  # end

  # with_options numericality: { other_than: 1, message: '項目を選択して下さい' } do
  #   validates :category_id
  #   validates :condition_id
  #   validates :shipping_charger_id
  #   validates :shipping_from_id
  #   validates :days_to_shipping_id
  # end
end

app/models/destination_article.rb
class DestinationArticle < ApplicationRecord
  belongs_to :destination
  belongs_to :article
end

app/models/line.rb
class Line < ActiveHash::Base
  self.data = [
    { id: 1, name: '86, 100, 106, 110, 206' },
    { id: 2, name: '101, 205' },
    { id: 3, name: '南5, 105' },
    { id: 4, name: '5, 17, 100' },
    { id: 5, name: '205, 206' },
    { id: 6, name: 'IT' },
    { id: 7, name: 'エンタメ' },
    { id: 8, name: 'スポーツ' },
    { id: 9, name: 'グルメ' },
    { id: 10, name: 'その他' }
  ]

  include ActiveHash::Associations
  belongs_to :destination
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :articles

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth
  # before_action :search_article


  def index
    @destination = Destination.all
  end

  # def search
  #   @results = @p.result.includes(:destination)
  # end

  def search
    @articles = Article.search(params[:keyword])
  end


  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :first_name, :family_name])
  end

  # def search_article
  #   @p = Article.ransack(params[:q])
  #   @articles = @p.result
  #   # @p = Article.ransack(params[:q])
  # end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'admin' && password == '2222'
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  before_action :set_destination, only: [:index]
  # before_action :search_article, only: [:index, :search]


  def index
    # redirect_to root_path unless current_user.id != @item.user_id
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to root_path
    else
    #   @destination = Destination.find(params[:destination_id])
      render action: :index
      # redirect_to root_path
    end
  end

  # def search
  #   # @destinations = Destination.search(params[:keyword])
  #   @articles = Article.search(params[:keyword])
  # end

  def show
    @article = Article.find(params[:id])
  end

  private

  def article_params
    params.require(:article).permit(:image, :title, :detail).merge(user_id: current_user.id, destination_id: params[:destination_id])
    # params.require(:article).permit(:title, :detail, destination_ids: []).merge(user_id: current_user.id,)
  end

  def set_destination
    @destination = Destination.find(params[:destination_id])
  end

end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController

  before_action :authenticate_user!, only: [:new]
  before_action :set_item, only: [:show, :update, :edit, :destroy]
  # before_action :search_article, only: [:show, :search]
  # before_action :move_to_index, except: [:index, :show, :search]

  def index
    @destinations = Destination.all.order('created_at DESC')
  end

  def new
    @destination = Destination.new
  end

  def create
    @destination = Destination.new(destination_params)
    if @destination.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show

    @destinations = Destination.all.order('created_at DESC')
    @destinations = @destination
    # @article = Article.find(params[:id])
    @articles = @destination.articles.includes(:user)
  end

  def search
    # @destinations = Destination.search(params[:keyword])
    # @article = Article.all
    # @articles = @destinations.articles.includes(:user)
    # @articles = Article.find_by(id: params[:destination_id])
    # @results = @p.result.includes(:destination) 
    @articles = Article.search(params[:keyword])
  end

  def edit
    redirect_to root_path unless current_user.id == @item.user.id
  end

  def update
    @item.update(item_params)
    if @item.save
      redirect_to item_path
    else
      render :edit
    end
  end

  def destroy
    redirect_to root_path unless current_user.id != @item.user.id
    @item.destroy
  end

  private

  def destination_params
    # params.require(:destination).permit(:name, :bus_stop_id, :line_id, :image)
    params.require(:destination).permit(:name, :bus_stop_id, :line_id, images: [])
  end

  def set_item
    @destination = Destination.find(params[:id])
  end

  # def search_article
  #   @p = Article.ransack(params[:q])
  # end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/articles/index.html.erb
<div class = "main-back">

<%= render "shared/header" %>

<div class = "main">

<div class='transaction-contents'>
  <div class='transaction-main'>
    <h1 class='transaction-title-text'>
      目的地に関する投稿
    </h1>
    <%# 購入内容の表示 %>
    <%# <div class='buy-item-info'> %>
      <%# <%= image_tag @item.image, class: 'buy-item-img' %>
      <%# <div class='buy-item-right-content'> %>
        <h2 class='buy-item-text'>
          <%= @destination.name %>
        </h2>

      </div>
    </div>
    <%# /購入内容の表示 %>

    <%= form_with model: @article, url: destination_articles_path, id: 'charge-form', class: 'transaction-form-wrap',local: true do |f| %>

        <%= render 'shared/error_messages', model: f.object %>

    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        投稿写真
        <%# <span class="indispensable">必須</span> %>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
        <%# <%= f.file_field :images, direct_upload: true, multiple: true %>
      </div>
    </div>
    <%# /出品画像 %>
    
    <%# 配送先の入力 %>
    <div class='shipping-address-form'>
      <h1 class='info-input-haedline'>
        配送先入力
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">タイトル</label>
          <%# <span class="indispensable">必須</span> %>
        </div>
        <%= f.text_field :title, class:"input-default", id:"postal-code", placeholder:"タイトル", maxlength:"30" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">内容</label>
          <%# <span class="indispensable">必須</span> %>
        </div>
        <%= f.text_area :detail, class:"input-default", id:"city", placeholder:"内容", rows: "10" %>
      </div>

    <div class='buy-btn'>
      <%= f.submit "投稿する" ,class:"buy-red-btn" %>
    </div>
    <% end %>
  </div>
</div>
<%# <%= render "shared/second-footer"%>

<%# 
      <%= form.text_field :image, placeholder: "Image Url" %>
      <%# <%= form.text_area :text, placeholder: "text", rows: "10" %>
      <%# <%= form.submit "SEND" %>

app/views/articles/show.html.erb
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">投稿者</th>
          <td class="detail-value"><%= @article.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">投稿日</th>
          <td class="detail-value"><%= @article.created_at %></td>
        </tr>
        <tr>
          <th class="detail-item">タイトル</th>
          <td class="detail-value"><%= @article.title %></td>
        </tr>
        <tr>
          <th class="detail-item">内容</th>
          <td class="detail-value"><%= @article.detail %></td>
        </tr>

      </tbody>
    </table>

    <div class="sell-btn-contents">
      <%=link_to 'もどる', destination_path, class:"back-btn" %>
    </div>

app/views/destinations/edit.html.erb
<%# cssは商品出品のものを併用しています。
app/assets/stylesheets/items/new.css %>

<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item, url: item_path, local: true do |f| %>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
    <%= render 'shared/error_messages', model: f.object %>
    <%# //インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>

    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        出品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /出品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :description, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:condition_id, Condition.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 配送について %>
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
        <a class="question" href="#">?</a>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_charger_id, ShippingCharger.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_from_id, ShippingFrom.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:days_to_shipping_id, DaysToShipping.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      </div>
    </div>
    <%# /配送について %>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :value, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
          </span>
        </div>
      </div>
    </div>
    <%# /販売価格 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', item_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer>
</div>

app/views/destinations/index.html.erb
<div class='main-back'>

<%= render "shared/header" %>


<div class='main'>


　 <ul class='item-lists'>

     <% @destinations.each do |destination| %>

        <li class='list'>

          <%= link_to destination_path(destination.id) do %>

           <%# <div class="destinations"> %>
              <%# <%= image_tag destination.image.variant(resize: '500x500'), class: "item-img" if destination.image.attached? %> 
           <%# </div> %>

          <%# <div class='item-img-content' style="background-image: url(<%= destination.image %>
          <%# <%= image_tag destination.image, class: "item-img" if destination.image.attached? %>

        <%# <%= destination.images.each do |image|%>
        <% if destination.images.count > 0 %>
          <div class='item-img-content' style="background-image: url(<%= destination.images %>);">
          <%= image_tag destination.images.first, class: "item-img" %>
         </div>
        <% end %>

        <div class='item-info'>
          <h3 class='item-name'>
            <%= destination.name %>
          </h3>

        </div>
        <% end %>
       <% end %>
      </li> 



  <%# 商品一覧 %>

  <%# /商品一覧 %>
</div>
<div class='purchase-btn'>
  <span class='purchase-btn-text'>出品する</span>

  <a href = destinations/new>
    <%= image_tag 'camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
  </a>
</div>

<%# <%= render "shared/footer" %>


</div>

app/views/destinations/search.html.erb
<div class='main-back'>

<%= render "shared/header" %>


<div class='main'>



<%# <%= form_with(url: search_destinations_path, local: true, method: :get, class: "search-form") do |form| %>
  <%# <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%# <%= form.submit "検索", class: "search-btn" %>
<%# <% end %>
 <%# <div class="contents row"> %>
  <%# <% @articles.each do |article| %>
    <%# <%= render partial: "destination", locals: { destination: destination } %>
   <%# <% end %>
 <%# </div>  %>


<div class = "table-back">

     <% @articles.each do |article| %>
     <%# <% locals: { article: article } %>




    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">投稿者</th>
          <td class="detail-value"><%= article.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">投稿日</th>
          <td class="detail-value"><%= article.created_at %></td>
        </tr>
        <tr>
          <th class="detail-item">タイトル</th>
          <td class="detail-value"><%= article.title %></td>
        </tr>
        <tr>
          <th class="detail-item">内容</th>
          <td class="detail-value"><%= article.detail %></td>
        </tr>
        <tr>
          <th class="detail-item">画像</th>
          <td class='item-img-content' style="background-image": url ><%= image_tag article.image, class: "article_image_item-img" %></td>
        </tr>

          

      </tbody>
    </table>

  <% end %>

  </div>

  </div>
  </div>

app/views/destinations/show.html.erb
<div class = "main-back">

<%= render "shared/header" %>

<div class = "main">

<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
   <h1>目的地</h1>
    <h2 class="another-item">
      <%= @destination.name %>
    </h2>


    <%# <%= image_tag @destination.image.variant(resize: '400x400'), class: "item-img" if @destination.image.attached? %>
  <%# <%= @destination.images.each do |image|%>
    <%# <%= image_tag image.variant(resize: '500x500'), class: "item-img" %>
  <%# <% end %>

        <% if @destination.images.count > 0 %>
          <div class='item-img-content' style="background-image: url(<%= @destination.images %>);">
          <%= image_tag @destination.images.second, class: "bus_stop_item-img" %>
         </div>
        <% end %>


    <table class="info-table">
      <tbody>
        <tr>
          <th class="info-item">バス停</th>
          <td class="info-value"><%= @destination.bus_stop.name %></td>
        </tr>
        <tr>
          <th class="info-item">路線</th>
          <td class="info-value"><%= @destination.line.name %></td>
        </tr>

      </tbody>
    </table>


     <%# <% @article.each do |article| %> 
    <%# <% if @article.empty? %>
      <%# <li class='list'> %>
        <%# <%= link_to '#' do %>
        <%# <%= image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/10/a004.png", class: "item-img" %>
        <%# <div class='item-info'> %>
          <%# <h3 class='item-name'> %>
            <%# 商品を出品してね！ %>
          <%# </h3> %>
              <%# <%= image_tag "star.png", class:"star-icon" %>
            <%# </div> %>
          <%# </div> %>
        <%# </div> %>
        <%# <% end %> 



    <%= link_to '状況を投稿しよう！', destination_articles_path(@destination.id), method: :get, class:"item-red-btn"%>

<div class = "table-back">

     <% @articles.each do |article| %>




    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">投稿者</th>
          <td class="detail-value"><%= article.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">投稿日</th>
          <td class="detail-value"><%= article.created_at %></td>
        </tr>
        <tr>
          <th class="detail-item">タイトル</th>
          <td class="detail-value"><%= article.title %></td>
        </tr>
        <tr>
          <th class="detail-item">内容</th>
          <td class="detail-value"><%= article.detail %></td>
        </tr>
        <tr>
          <th class="detail-item">画像</th>
          <td class='item-img-content' style="background-image": url ><%= image_tag article.image, class: "article_image_item-img" %></td>
        </tr>
        
        <%# article.images.each do |image| %>
          <%#= image_tag image, class: "item-img" %>
          <%# end %>

          

      </tbody>
    </table>



    <% end %>

</div>

</div>

</div>

<%# articleを表示する %>
    <%# <% if @article = nil %> 
    <%# <% then %> 
      <%# <li class='list'> %>
        <%# <%= link_to '#' do %> 
        <%# <%= image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/10/a004.png", class: "item-img" %>
        <%# <div class='item-info'> %>


        <%# </div> %>
        <%# <% end %> 
      <%# </li> %>
    <%# <% else %> 
     <%# <% @articles.each do |article| %>
        <%# <li class='list'> %>
          <%# <%= link_to destination_article_path(article.id) do %>


      <%# <% end %>

    <%# <% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>京都バスガイド</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%= javascript_pack_tag 'application' %>
</head>




<body>
  <%= yield %>

  <%# <% background-image:  url(images/kabegami.jpg); %>

</body>

</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分
<div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    だれでもかんたん、人生を変えるフリマアプリ
  </p>
  <h2 class='ad-footer-title'>
    今すぐ無料ダウンロード！
  </h2>
  <div class='store-btn'>
    <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
    <%# <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
  <%# </div> %> 
<%# </div> %>
<%# /下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMA利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li> 
      # </ul>
    # </div>
    # <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li> 
        <li><%= link_to 'ブランド一覧', "#", class: "footer-link" %></li> 
       </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to 'FURIMAガイド', "#", class: "footer-link"%></li> 
        <li><%= link_to 'FURIMAロゴ利用ガイドライン', "#", class: "footer-link" %></li> 
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li> 
      </ul>
    </div>
  </div>
  <%= link_to image_tag("furima-logo-white.png", class:"logo-white"), "#"%> 
  <p>© FURIMA</p>
</div> 

app/views/shared/_header.html.erb
<%# <% CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
   <%# <div class='search-bar-contents'> %>

   <%# <%= form_with(url: search_destinations_path , local: true, method: :get, class: "search-form") do |form| %>


<%= link_to image_tag("logo.png", class:"furima-icon"), "/" %>

  <%= form_with(url: search_destinations_path , local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
  <% end %>

<%# 
<h1>
  商品検索
</h1>
<%= search_form_for @p, url: articles_search_path do |f| %>
<%# <%= search_form_for @p do |f| %>
  <%# <%= f.label :detail_eq, '商品名' %>

  <%# <%= f.search_field :detail_cont, placeholder: "投稿を検索する", class: "search-input" %>



  <%# <%= f.collection_select :name_eq, @products, :name, :name,  include_blank: '指定なし' %>
  <%# <br> %>
  <%# <%= f.submit '検索' %>
<%# <% end %>



    <%# <form class="search-form" action="#"> %>
      <%# <input class='input-box' placeholder='キーワードから探す'> %>
      <%# <button class="search-button"> %>
        <%# <%= image_tag "search.png", class:"search-icon" %>
      <%# </button> %>
    <%# </form> %>
  <%# </div> %>
  <%# <div class='nav'> %>

    <ul class='lists-right'>

    <% if user_signed_in? %>
      <li><%= link_to current_user.nickname, "#", class: "user-nickname" %></li> 
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>

    <% else %>
      <li><%= link_to 'ログイン', user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
    <% end %>
    </ul>
  <%# </div> %>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>FURIMA利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <%= image_tag "logo.png", class:"second-fotter-logo"%>
</footer>